---
# tasks file for setup-apache-role
- name: install git package
  yum:
    name: git
    state: installed

- name: uninstall httpd package
  yum:
    name: httpd
    state: installed
  notify: start httpd service

- name: install npm package
  yum:
    name: npm.x86_64
    state: installed
  notify: create a directory in ansadmin as npm_dir

- name: copy index.html
  copy:
    src: /home/ansadmin/index.html
    dest: /var/www/html
    mode: 0777

