---
- name: install httpd and start service playbook
  hosts: Nodes
  become: true 
  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: present
    notify: start httpd    

  handlers:
  - name: start httpd
    service:
      name: httpd
      state: started    

  
